### ISSUE TITLE
Crashing when importing VAE.py

### ISSUE THREAD

**Issue by EJShim** [ajbrock/Generative-and-Discriminative-Voxel-Modelling#3]
Currently, I am using

Windows 10
Python 3.6
VTK 7.1.0

If i try to run GUI.py, I get Error from 

config_module = imp.load.source('config', args.config_path)

saying "unmarshallable object"

**Comment by ajbrock** [comment]
This is due to discrepancies between python 2 and 3. Either install python 2.7 or replace the imp.load_source calls with
` __import__('config',args.config_path[:-3])`

 (the "[:-3]" will get rid of the .py entered from the command line, and is also an adorable kitty emoticon). 

You'll also need to handle other python2-3 shenanigans like making sure any xrange calls are replaced with range, etc.
