### ISSUE TITLE
higher data dimension?

### ISSUE THREAD

**Issue by EJShim** [ajbrock/Generative-and-Discriminative-Voxel-Modelling#4]
Hello, I seek your advice

Could be there any problem if I re-train this network using higher dimension , such as 256x256x256

or 500x500x20?

Furthermore, can grayscale(not -1,3 binary) image volume also be used?

**Comment by ajbrock** [comment]
Hi EJ,

Higher resolutions are possible, but you'll quickly find that you run up against memory limitations unless you have enough GPUs to handle your chosen resolution. The curse of dimensionality is even worse in 3D! You may also run into some issues when trying to run the GUI at higher resolutions as VTK doesn't seem to like the way I do things when using high-res voxel grids (I've run some tests at like 128x128x128 on a different problem and it didn't entirely work out). 

I'd recommend taking note of the recent [Octree Generating Networks](https://arxiv.org/abs/1703.09438)  and [OctNet](https://arxiv.org/abs/1611.05009) for more efficient ways of dealing with higher resolutions for either one of these tasks; I don't currently have any source code to support octrees, so you'd need to look into getting source from each paper, respectively. 

Network design-wise, you'll also want to make use of some of the simple recent tips such as using 1x1 convs to reduce the number of channels at each block before spatial convs, and using 1x1convs to do compression at downsampling blocks--the [DenseNet](https://arxiv.org/abs/1608.06993) paper has some good examples of effective designs that use these.

As to grayscale, you can definitely do that--if you want to do something like measure the amount which the mesh fills in each volume element, that may lead to improvements on the discriminative task. I stuck to binary for this project so that the representations would be compatible with both the GUI and the classifier nets, but there's no reason why you couldn't voxelize to grayscale (or if you have medical data like a CT scan, it may already be grayscale in HUs and whatnot).

Hope that helps, and sorry for the delayed response (ICLR distracted me <_<)
